# Generated by Django 5.2.7 on 2025-10-18 16:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(default='SmartSales365', max_length=200, verbose_name='Nombre de la Empresa')),
                ('legal_name', models.CharField(default='SmartSales365 S.A. de C.V.', max_length=200, verbose_name='Razón Social')),
                ('rfc', models.CharField(default='SSA123456789', max_length=13, verbose_name='RFC')),
                ('address', models.TextField(default='Av. Tecnología 123, Col. Digital, CDMX', verbose_name='Dirección')),
                ('phone', models.CharField(default='+52 55 1234 5678', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(default='info@SmartSales365.com', max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, default='https://SmartSales365.com', verbose_name='Sitio Web')),
                ('logo', models.ImageField(blank=True, upload_to='company/logos/', verbose_name='Logo')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='Tasa de Impuestos (%)')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='Moneda')),
                ('timezone', models.CharField(default='America/Mexico_City', max_length=50, verbose_name='Zona Horaria')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, upload_to='profiles/avatars/', verbose_name='Avatar')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('seller', 'Vendedor'), ('cashier', 'Cajero')], default='seller', max_length=20, verbose_name='Rol')),
                ('is_online', models.BooleanField(default=False, verbose_name='En línea')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Última IP')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Última Actividad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
