# Generated by Django 5.2.7 on 2025-10-18 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('transfer', 'Transferencia'), ('crypto', 'Criptomoneda')], max_length=20, verbose_name='Método de pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID de Transacción')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='ID Externo')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='Moneda')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisión')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Neto')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Motivo de Fallo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='Número de Intento')),
                ('status', models.CharField(choices=[('initiated', 'Iniciado'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], max_length=20, verbose_name='Estado')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='Código de Error')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Datos de Respuesta')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Intento de Pago',
                'verbose_name_plural': 'Intentos de Pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('external_refund_id', models.CharField(blank=True, max_length=100, verbose_name='ID de Reembolso Externo')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('event_type', models.CharField(max_length=50, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('response_status', models.CharField(blank=True, max_length=10, verbose_name='Estado de Respuesta')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='payments.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Webhook de Pago',
                'verbose_name_plural': 'Webhooks de Pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
