# Generated by Django 5.2.7 on 2025-10-18 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_online', models.BooleanField(default=False, verbose_name='Pago Online')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='paymentwebhook',
            options={'ordering': ['-created_at'], 'verbose_name': 'Webhook Stripe', 'verbose_name_plural': 'Webhooks Stripe'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='paymentrefund',
            name='external_refund_id',
        ),
        migrations.RemoveField(
            model_name='paymentwebhook',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='paymentwebhook',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentwebhook',
            name='response_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Falló en'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Procesado en'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Charge'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Payment Intent'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Refund'),
        ),
        migrations.AddField(
            model_name='paymentwebhook',
            name='data',
            field=models.JSONField(default=dict, verbose_name='Datos'),
        ),
        migrations.AddField(
            model_name='paymentwebhook',
            name='stripe_event_id',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='ID Event'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True, verbose_name='Razón del Fallo'),
        ),
        migrations.AlterField(
            model_name='paymentrefund',
            name='reason',
            field=models.CharField(blank=True, max_length=100, verbose_name='Razón'),
        ),
        migrations.AlterField(
            model_name='paymentrefund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('succeeded', 'Exitoso'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='paymentwebhook',
            name='event_type',
            field=models.CharField(default='', max_length=100, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod', verbose_name='Método de Pago'),
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('stripe_customer_id', models.CharField(max_length=100, unique=True, verbose_name='ID Customer')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Cliente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente Stripe',
                'verbose_name_plural': 'Clientes Stripe',
            },
        ),
        migrations.DeleteModel(
            name='PaymentAttempt',
        ),
    ]
