# Generated by Django 5.2.7 on 2025-10-26 21:35

from django.db import migrations

def create_payment_methods(apps, schema_editor):
    """Crear métodos de pago por defecto"""
    PaymentMethod = apps.get_model('payments', 'PaymentMethod')
    
    # Métodos de pago por defecto
    default_methods = [
        {
            'name': 'Tarjeta de Crédito/Débito',
            'code': 'stripe',
            'is_active': True,
            'is_online': True,
            'icon': 'credit-card',
            'description': 'Pago seguro con tarjeta de crédito o débito',
            'sort_order': 1
        },
        {
            'name': 'Efectivo',
            'code': 'cash',
            'is_active': True,
            'is_online': False,
            'icon': 'money-bill',
            'description': 'Pago en efectivo al recibir el producto',
            'sort_order': 2
        },
        {
            'name': 'Transferencia Bancaria',
            'code': 'transfer',
            'is_active': True,
            'is_online': False,
            'icon': 'university',
            'description': 'Transferencia bancaria directa',
            'sort_order': 3
        }
    ]
    
    for method_data in default_methods:
        PaymentMethod.objects.get_or_create(
            code=method_data['code'],
            defaults=method_data
        )

def reverse_create_payment_methods(apps, schema_editor):
    """Eliminar métodos de pago por defecto"""
    PaymentMethod = apps.get_model('payments', 'PaymentMethod')
    PaymentMethod.objects.filter(code__in=['stripe', 'cash', 'transfer']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_alter_paymentwebhook_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_payment_methods, reverse_create_payment_methods),
    ]
