# Generated by Django 5.2.7 on 2025-10-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(default='México', max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('client_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Empresa')], default='individual', max_length=20, verbose_name='Tipo de Cliente')),
                ('segment', models.CharField(choices=[('vip', 'VIP'), ('regular', 'Regular'), ('new', 'Nuevo')], default='new', max_length=20, verbose_name='Segmento')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('avatar', models.ImageField(blank=True, upload_to='clients/avatars/', verbose_name='Avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True, verbose_name='Última Compra')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de Compras')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
