# Generated by Django 5.2.7 on 2025-10-18 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('report_type', models.CharField(choices=[('sales', 'Ventas'), ('products', 'Productos'), ('clients', 'Clientes'), ('financial', 'Financiero'), ('inventory', 'Inventario'), ('predictions', 'Predicciones')], max_length=50, verbose_name='Tipo de Reporte')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('json', 'JSON'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Formato')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parámetros')),
                ('prompt', models.TextField(blank=True, verbose_name='Prompt Original')),
                ('source', models.CharField(choices=[('text', 'Texto'), ('voice', 'Voz')], default='text', max_length=10, verbose_name='Fuente')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Ruta del archivo')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño del archivo')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Generado en')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('report_type', models.CharField(choices=[('sales', 'Ventas'), ('products', 'Productos'), ('clients', 'Clientes'), ('financial', 'Financiero')], max_length=50, verbose_name='Tipo de Reporte')),
                ('parameters', models.JSONField(verbose_name='Parámetros')),
                ('schedule_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral')], max_length=20, verbose_name='Tipo de Programación')),
                ('schedule_time', models.TimeField(verbose_name='Hora de Ejecución')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Ejecución')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Programación de Reporte',
                'verbose_name_plural': 'Programaciones de Reportes',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('report_type', models.CharField(choices=[('sales', 'Ventas'), ('products', 'Productos'), ('clients', 'Clientes'), ('financial', 'Financiero')], max_length=50, verbose_name='Tipo de Reporte')),
                ('template_data', models.JSONField(verbose_name='Datos de Plantilla')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reportes',
            },
        ),
    ]
